In [2]:
# Import Statements
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
# Import in the CSV file
df = pd.read_csv('/home/data_scientist/checkin_dataset.csv')
df = df.drop('Unnamed: 0',axis=1) # Delete the unnamed column
df.head(10)   # check to see first 10 rows

   user            timestamp  xcoordinate  ycoordinate
0    12  2017-07-13 09:36:00     0.906835     0.776484
1    12  2017-07-30 15:23:00     0.928587     0.804964
2    12  2017-05-05 00:41:00     0.904091     0.784043
3    12  2017-07-26 06:10:00     0.906752     0.804461
4    12  2017-05-22 13:22:00     0.900641     0.781683
5    12  2017-06-11 13:05:00     0.899680     0.790893
6     8  2017-07-13 09:40:00     0.873765     0.808707
7     8  2017-07-30 15:23:00     0.913476     0.789742
8     8  2017-05-05 00:43:00     0.915256     0.790685
9     8  2017-07-26 06:12:00     0.916273     0.785860

In [124]:
# With this cell I am creating a new DataFrame that allows me to see all of 
# the median or 50th percentile values for each users x and y coordinates
d = []
for i in range(0,100):
    x_describe = df[df.user == i]['xcoordinate'].describe()
    y_describe = df[df.user == i]['ycoordinate'].describe()
    x_med = x_describe[5]
    y_med = y_describe[5]
    d.append((i,x_med,y_med))

df_update = pd.DataFrame(d,columns=('user','xcoordinate median','ycoordinate median'))
display(df_update)

    user  xcoordinate median  ycoordinate median
0      0            0.587523            0.572058
1      1            0.379256            0.143200
2      2            0.418005            0.333097
3      3            0.598273            0.590565
4      4            0.898637            0.727847
5      5            0.235681            0.127525
6      6            0.378529            0.117303
7      7            0.226427            0.127971
8      8            0.394654            0.325326
9      9            0.399778            0.138013
10    10            0.236775            0.030494
11    11            0.831474            0.723564
12    12            0.240898            0.330969
13    13            0.377889            0.061959
14    14            0.825397            0.805879
15    15            0.364098           -0.034160
16    16            0.827838            0.793731
17    17            0.368266            0.140306
18    18            0.846488            0.732250
19    19            0.574251            0.859033
20    20            0.400470            0.137268
21    21            0.760509            0.651713
22    22            0.254382            0.319095
23    23            0.384969            0.067418
24    24            0.853373            0.846463
25    25            0.366784           -0.023618
26    26            0.237141            0.135246
27    27            0.739276            0.583354
28    28            0.373753            0.053376
29    29            0.848641            0.854650
..   ...                 ...                 ...
70    70            0.375256            0.068890
71    71            0.594976            0.571515
72    72            0.369939            0.045960
73    73            0.749948            0.732305
74    74            0.597252            0.719787
75    75            0.258213            0.325788
76    76            0.217232            0.022316
77    77            0.264753            0.311613
78    78            0.932763            0.807709
79    79            0.251871            0.144676
80    80            0.403414            0.137245
81    81            0.411834            0.070281
82    82            0.743998            0.580929
83    83            0.221308           -0.038456
84    84            0.226393            0.023962
85    85            0.412773            0.064245
86    86            0.227923            0.040201
87    87            0.596622            0.897133
88    88            0.230978            0.074626
89    89            0.382182            0.052030
90    90            0.912575            0.747325
91    91            0.596132            0.577394
92    92            0.335446            0.054936
93    93            0.359566            0.323021
94    94            0.756608            0.588705
95    95            0.409083            0.140745
96    96            0.236089            0.053701
97    97           -0.118936            0.055726
98    98            0.875375            0.862784
99    99            0.223160            0.318899

[100 rows x 3 columns]

From the given data above we can determine what x coordinate and what y coordinate the the user is most often at using the medians found for the x and y. What this means is that we are able to see not what locations they are most generally at.

In [125]:
# What this cell allows us to do is find the mode of the data that we just
# generated
temp1 = round(df_update['xcoordinate median'].mode(),4)
temp2 = round(df_update['ycoordinate median'].mode(),4)
x_mode = round(temp1.value_counts().idxmax(),4)
y_mode = round(temp2.value_counts().idxmax(),4)
display(x_mode)
display(y_mode)

0.74990000000000001

0.14319999999999999

From the 2 values that are displayed above what we can conclude about the data that we have gathered is the top one is the x coordinate mode and the bottom one is the y coordinate mode. With this information we can decide that these are the two most popular coordinates that were visited for all users.